(require (lib "graphics.ss" "graphics"))
(open-graphics)

(define fondo (open-pixmap "fondo" (make-posn 800 389)))
(define ventana (open-viewport "burns" (make-posn 800 389)))
((draw-pixmap ventana) "back3.png" (make-posn 0 0))
(define z1l "z1l.png")
(define z1r "z1r.png")
(define z2l "z2l.png")
(define z2r "z2r.png")
(define z3l "z3l.png")
(define z3r "z3r.png")
(define z4l "z4l.png")
(define z4r "z4r.png")
(define z5l "z5l.png")
(define z5r "z5r.png")
(define z6l "z6l.png")
(define z6r "z6r.png")
(define mov1 "b1.png")
(define mov2 "b2.png")
(define mov3 "b3.png")
(define mov4 "b4.png")
(define mov1l "b1l.png")
(define mov2l "b2l.png")
(define mov3l "b3l.png")
(define mov4l "b4l.png")
(define bala1r "bala1r.png")
(define bala1l "bala1l.png")

(define vector (make-vector 40))
(vector-set! vector 0 0)
(vector-set! vector 1 0)
(vector-set! vector 2 0)
(vector-set! vector 3 0)
(vector-set! vector 4 0)
(vector-set! vector 5 0)
(vector-set! vector 6 0)
(vector-set! vector 7 0)
(vector-set! vector 8 0)
(vector-set! vector 9 0)
(vector-set! vector 10 0)
(vector-set! vector 11 0)
(vector-set! vector 12 0)
(vector-set! vector 13 0)
(vector-set! vector 14 0)
(vector-set! vector 15 0)
(vector-set! vector 16 0)
(vector-set! vector 17 0)
(vector-set! vector 18 0)
(vector-set! vector 19 0)
(vector-set! vector 20 0)
(vector-set! vector 21 0)
(vector-set! vector 22 0)
(vector-set! vector 23 0)
(vector-set! vector 24 0)
(vector-set! vector 25 0)
(vector-set! vector 26 0)
(vector-set! vector 27 0)
(vector-set! vector 28 0)
(vector-set! vector 29 0)
(vector-set! vector 30 0)
(vector-set! vector 31 0)
(vector-set! vector 32 0)
(vector-set! vector 33 0)
(vector-set! vector 34 0)
(vector-set! vector 35 0)
(vector-set! vector 36 0)
(vector-set! vector 37 0)
(vector-set! vector 38 0)
(vector-set! vector 39 0)


(define (mov-img-zombie-left x)
  (cond
    ((= x 0) z1l)
    ((= x 1) z2l)
    ((= x 2) z3l)
    ((= x 3) z4l)
    ((= x 4) z5l)
    ((= x 5) z6l)
    )
  )
(define (mov-img-zombie-right x)
  (cond
    ((= x 0) z1r)
    ((= x 1) z2r)
    ((= x 2) z3r)
    ((= x 3) z4r)
    ((= x 4) z5r)
    ((= x 5) z6r)
    )
  )
(define (mov-img-burns-right x)
  (cond
    ((= x 0) mov1)
    ((= x 1) mov2)
    ((= x 2) mov3)
    ((= x 3) mov4)
    )
  )

(define (mov-img-burns-left x)
  (cond
    ((= x 0) mov1l)
    ((= x 1) mov2l)
    ((= x 2) mov3l)
    ((= x 3) mov4l)
    )
  )

(define (mov-img-bala x)
  (cond
    ((= x 0) bala1r)
    ((= x 1) bala1l)
    )
  )


(define (mov-burns-right  x y t)
  (if (or (equal? (key-value (get-key-press ventana)) 'left) (= y 4))
      (consola x 0 (key-value (get-key-press ventana)) t)
      (begin
        ((draw-pixmap fondo) "back3.png" (make-posn 0 0)) 
        (((draw-pixmap-posn (mov-img-burns-right (remainder y 4))) fondo) (make-posn x 90))
        (copy-viewport fondo ventana)
        (clear-viewport fondo)
        (mov-burns-right  (+ x 10)  (+ y 1) (+ t 1))
        )
      )
  )
  

(define (mov-burns-left   x y t)
  (if (or (equal? (key-value (get-key-press ventana)) 'right) (= y 4))
      (consola x 0 (key-value (get-key-press ventana)) t)
      (begin
        ((draw-pixmap fondo) "back3.png" (make-posn 0 0)) 
        (((draw-pixmap-posn (mov-img-burns-left (remainder y 4))) fondo) (make-posn x 90))
        (copy-viewport fondo ventana)
        (clear-viewport fondo)
        (mov-burns-left   (- x 10)  (+ y 1) (+ t 1))
        )
      )  
  )

(define (mov-bala-left  x y z)
  (if (or  (>= x 480) (<= x -390))
      (consola z 0 (key-value (get-key-press ventana)) t)
      (begin
        ((draw-pixmap fondo) "back3.png" (make-posn 0 0))
        (((draw-pixmap-posn (mov-img-burns-left 3)) fondo) (make-posn z 90))
        (((draw-pixmap-posn (mov-img-bala 1)) fondo) (make-posn x 90))
        (copy-viewport fondo ventana)
        (clear-viewport fondo)
        (mov-bala-left  (- x 90) y z)
        )
      )
  )

(define (mov-bala-right  x y z)
 (if (or (>= x 480) (<= x -330))
      (consola z 0 (key-value (get-key-press ventana)) t)
      (begin
        ((draw-pixmap fondo) "back3.png" (make-posn 0 0))
        (((draw-pixmap-posn (mov-img-burns-right 3)) fondo) (make-posn z 90))
        (((draw-pixmap-posn (mov-img-bala 0)) fondo) (make-posn x 90))
        (copy-viewport fondo ventana)
        (clear-viewport fondo)
        (mov-bala-right  (+ x 90) y z)
        )
      ))

(define (consola x y press t) 
  (cond
    ( (and (> x -290) (equal? press 'left))  (mov-burns-left   x y t))
    ( (and (< x 440)(equal? press 'right)) (mov-burns-right  x y t))
    ( (equal? press 'up) (mov-bala-right  x y x))
    ( (equal? press 'down) (mov-bala-left  x y x))
    (else (consola x y (key-value (get-key-press ventana)) t))
    )
  )



     
(consola  75 1 'left 0)

